obj-m := android_module.o
KBUILD_EXTRA_SYMBOLS := /home/runner/work/f3311/f3311/MuDr/Module.symvers



all:
 make -C /home/runner/work/f3311/f3311/kernel-3.18/out/ M=$(shell pwd) modules
clean:
 make -C /home/runner/work/f3311/f3311/kernel-3.18/out/ M=$(shell pwd) clean
