name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
  
      
    - name: Install dependencies
      run:  ./env.sh; cd kernel-3.18; make O=out ARCH=arm bassoon_defconfig
      
    - name: Run check
      run: ./env.sh; cd kernel-3.18; make -j8 O=out ARCH=arm
      
    
