name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v2
  
      
    - name: Install dependencies
      run:  source ./env.sh; cd kernel-3.18; make O=out ARCH=arm bassoon_defconfig
      
    - name: Run check
      run: source ./env.sh; cd kernel-3.18; make -j8 O=out ARCH=arm
      
    - name: Ls
      run: cd /home/runner/work/f3311/f3311/kernel-3.18/out; ls



    - name: copy file
      uses: actions/upload-artifact@v2
      with:
        name: my_doc
        path: /home/runner/work/f3311/f3311/kernel-3.18/out
  
    
