name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
  
      
    - name: Install dependencies
      run:  source ./env.sh; cd kernel-3.18; make O=out ARCH=arm KERNELRELEASE=3.18.19+ bassoon_defconfig
      
    - name: compil
      run: source ./env.sh; cd kernel-3.18; make -j8 O=out ARCH=arm KERNELRELEASE=3.18.19+
      
    - name: prepare copy
      run: mkdir final;  find kernel-3.18/out -name '*ko' -type f -exec cp '{}' final \;  ; find kernel-3.18/out -type f -iname '*' -maxdepth 1 -exec cp {} final \; ;
      
    - name: copy file
      uses: actions/upload-artifact@v2
      with:
        name: my_kernel
        path: kernel-3.18/out
      
    
