name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
  
      
    - name: Install dependencies
      run:  source ./env.sh; cd kernel-3.18; make O=out ARCH=arm KERNELRELEASE=3.18.19+ bassoon_defconfig
      


    - name: compil
      run: source ./env.sh; cp -f MuDr/Module.symvers kernel-3.18/ ; cp -f MuDr/Module.symvers kernel-3.18/out/ ; cd kernel-3.18; make -j4 O=out ARCH=arm KERNELRELEASE=3.18.19+ 
  
    - name: pakZip
      run: mkdir vrm ; cd vrm ; tar -zcf kern.tar.gz   /home/runner/work/f3311/f3311/kernel-3.18/out/
 
    - name: copy file
      uses: actions/upload-artifact@v2
      with:
        name: my_kernel
        path: vrm
      
    
